### ISSUE TITLE
Optimizar llamadas API.js

### ISSUE THREAD

**Issue by martindurn** [fseitun/Chuffen#25]
desde la api   (metodoPOST, metodoGET)
export const metodoDELETE = async(url, newObj) => {
    const { data } = await axios.post(`${PATH}${accion}${idSociedad}`, newObj);
    return data;
};
desde la pagina
import { metodoPOST } from 'src/components/API';
  const { mutate: sendValues } = useMutation(
    (nuevoDolar) => metodoPOST('dolar/agregar/' + idSociedad, nuevoDolar),
    {
      onSuccess: () => {
        queryClient.refetchQueries(['dolar', idSociedad]);
      }
    }
  );

**Comment by fseitun** [comment]
https://github.com/fseitun/Chuffen/blob/master/src/components/API.js
